<?php

return [
  "all" => [
    "abkhazia",
    "afghanistan",
    "aland islands",
    "albania",
    "algeria",
    "american samoa",
    "andorra",
    "angola",
    "anguilla",
    "antigua and barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "azores islands",
    "bahamas",
    "bahrain",
    "balearic islands",
    "bangladesh",
    "barbados",
    "basque country",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bonaire",
    "bosnia and herzegovina",
    "botswana",
    "brazil",
    "british columbia",
    "british indian ocean territory",
    "british virgin islands",
    "brunei",
    "bulgaria",
    "burkina faso",
    "burundi",
    "cambodia",
    "cameroon",
    "canada",
    "canary islands",
    "cape verde",
    "cayman islands",
    "central african republic",
    "ceuta",
    "chad",
    "chile",
    "china",
    "christmas island",
    "cocos island",
    "colombia",
    "comoros",
    "cook islands",
    "corsica",
    "costa rica",
    "croatia",
    "cuba",
    "curacao",
    "czech republic",
    "democratic republic of congo",
    "denmark",
    "djibouti",
    "dominica",
    "dominican republic",
    "east timor",
    "ecuador",
    "egypt",
    "el salvador",
    "england",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "ethiopia",
    "european union",
    "falkland islands",
    "fiji",
    "finland",
    "france",
    "french polynesia",
    "gabon",
    "galapagos islands",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guam",
    "guatemala",
    "guernsey",
    "guinea",
    "guinea bissau",
    "haiti",
    "hawaii",
    "honduras",
    "hong kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle of man",
    "israel",
    "italy",
    "ivory coast",
    "jamaica",
    "japan",
    "jersey",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "kosovo",
    "kwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "lomon islands",
    "luxembourg",
    "macao",
    "madagascar",
    "madeira",
    "malasya",
    "malawi",
    "maldives",
    "mali",
    "malta",
    "marshall island",
    "martinique",
    "mauritania",
    "mauritius",
    "melilla",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nato",
    "nauru",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "niue",
    "norfolk island",
    "northern cyprus",
    "northern marianas islands",
    "north korea",
    "norway",
    "oman",
    "ossetia",
    "pakistan",
    "palau",
    "palestine",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "pitcairn islands",
    "poland",
    "portugal",
    "puerto rico",
    "qatar",
    "rapa nui",
    "republic of macedonia",
    "republic of the congo",
    "romania",
    "russia",
    "rwanda",
    "saba island",
    "sahrawi arab democratic republic",
    "saint kitts and nevis",
    "samoa",
    "san marino",
    "sao tome and prince",
    "sardinia",
    "saudi arabia",
    "scotland",
    "senegal",
    "serbia",
    "seychelles",
    "sicily",
    "sierra leone",
    "singapore",
    "sint eustatius",
    "sint maarten",
    "slovakia",
    "slovenia",
    "somalia",
    "somaliland",
    "south africa",
    "south korea",
    "south sudan",
    "spain",
    "sri lanka",
    "st barts",
    "st lucia",
    "st vincent and the grenadines",
    "sudan",
    "suriname",
    "swaziland",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "tibet",
    "togo",
    "tokelau",
    "tonga",
    "transnistria",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "turks and caicos",
    "tuvalu",
    "tuvalu 1",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united nations",
    "united states",
    "uruguay",
    "uzbekistn",
    "vanuatu",
    "vatican city",
    "venezuela",
    "vietnam",
    "virgin islands",
    "wales",
    "yemen",
    "zambia",
    "zimbabwe",
  ],
];
